version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "a2ago"]
    volumes:
      - redis-data:/data
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: minio0admin
      MINIO_ROOT_PASSWORD: minio0admin
    command: server --console-address ":9001" /data
volumes:
  redis-data:
